In [1]:
from PIL import Image
import numpy as np
import os, sys
import numpy as np
import tifffile as tiff
# from tensorflow.keras.preprocessing.image import ImageDataGenerator
import itertools

In [7]:
a = np.random.random((3,5))


epsilon = 0.0000001

b = a/((1-a)+epsilon)


c = np.log2(b)
c

array([[ 0.84609509, -0.78553266, -1.1829349 , -1.09876101,  1.67115586],
       [-0.48756372,  1.97275739,  1.9904729 ,  1.31606284, -4.07493552],
       [ 3.33993287,  1.51068297, -2.75577037,  2.02680488, -0.23203789]])

In [9]:
def recycle():
    for i in range(5):
        yield i
        
a = itertools.cycle(recycle(),)


In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
a = np.ones((2,2)).astype('int8')
a[0,0] = 0
a = a * 4




b = np.where(a > 0, 1, 0)
b[0,0] = 2
b[0,1] = 3
print(a)
print(b)

a*b

[[0 4]
 [4 4]]
[[2 3]
 [1 1]]


array([[ 0, 12],
       [ 4,  4]])

2

In [14]:
Path = r'C:\Users\sunzh\CS636\Summer project\BPN\data'
os.path.isfile(Path + r'\FOV\FOV_%d%d%d_0.tif'%( 16,16,8))

True

In [18]:
a = np.zeros((2,2,2)).astype('float')
a[1] = 2
a[1,1] = 4
b = np.std(a)
c = np.mean(a)

d = a - c

e = np.concatenate((a,d), axis = 0)


dtype('float64')

In [1]:
imagepath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input.tif'
type(imagepath)

str

In [6]:
from config import Config


NameError: name 'config' is not defined

In [14]:
imagepath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input.tif'
Image = tiff.imread(imagepath)
Image = np.transpose(Image, (2,0,1))
# Image1 = np.transpose(Image, (2,0,1))

patch = Image[0:33,0:33,0:17]
tiff.imsave(r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input-patch.tif',patch)

In [11]:
help(tiff.imsave)

Help on function imwrite in module tifffile.tifffile:

imwrite(file, data=None, shape=None, dtype=None, **kwargs)
    Write numpy array to TIFF file.
    
    Refer to the TiffWriter class and its asarray function for documentation.
    
    A BigTIFF file is created if the data size in bytes is larger than 4 GB
    minus 32 MB (for metadata), and 'bigtiff' is not specified, and 'imagej'
    or 'truncate' are not enabled.
    
    Parameters
    ----------
    file : str or binary stream
        File name or writable binary stream, such as an open file or BytesIO.
    data : array_like
        Input image. The last dimensions are assumed to be image depth,
        height, width, and samples.
        If None, an empty array of the specified shape and dtype is
        saved to file.
        Unless 'byteorder' is specified in 'kwargs', the TIFF file byte order
        is determined from the data's dtype or the dtype argument.
    shape : tuple
        If 'data' is None, shape of an empty 

In [5]:
imagepathpatch = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input-patch.tif'
labelpath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-labels\train-labels.tif'

ImagePatch = tiff.imread(labelpath)
ImagePatch = np.transpose(ImagePatch, (2,0,1))
ImagePatch

array([[[333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        ...,
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1]],

       [[333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        ...,
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1]],

       [[333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        [333, 333, 333, ...,   1,   1,   1],
        ...,
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1]],

       ...,

       [[381, 381, 381, ...,   0,   0,   0],
        [381, 381, 381, ...,   0,   0,   0],
        [381, 381, 381, ...,   0,   0,   0

In [16]:
Image[0:33,0:33,0:17]

array([[[200, 210, 208, ..., 175, 177, 176],
        [204, 219, 232, ..., 233, 231, 218],
        [174, 173, 179, ..., 185, 184, 173],
        ...,
        [182, 184, 202, ..., 196, 199, 203],
        [183, 197, 217, ..., 224, 230, 234],
        [192, 190, 198, ..., 240, 234, 245]],

       [[184, 206, 210, ..., 173, 167, 175],
        [208, 216, 236, ..., 222, 221, 219],
        [169, 171, 182, ..., 186, 175, 165],
        ...,
        [195, 197, 213, ..., 179, 194, 201],
        [184, 200, 220, ..., 234, 232, 231],
        [201, 205, 199, ..., 241, 243, 239]],

       [[180, 194, 211, ..., 181, 175, 184],
        [207, 215, 226, ..., 224, 225, 214],
        [165, 172, 188, ..., 179, 173, 149],
        ...,
        [209, 205, 210, ..., 169, 196, 198],
        [186, 196, 206, ..., 227, 227, 229],
        [222, 216, 218, ..., 235, 244, 239]],

       ...,

       [[185, 175, 174, ..., 192, 182, 177],
        [182, 189, 188, ..., 191, 195, 222],
        [120, 138, 136, ..., 163, 146, 150

In [17]:
ImagePatch

array([[[200, 204, 174, ..., 182, 183, 192],
        [184, 208, 169, ..., 195, 184, 201],
        [180, 207, 165, ..., 209, 186, 222],
        ...,
        [185, 182, 120, ..., 166, 227, 219],
        [175, 176, 123, ..., 182, 226, 221],
        [163, 175, 130, ..., 192, 222, 224]],

       [[210, 219, 173, ..., 184, 197, 190],
        [206, 216, 171, ..., 197, 200, 205],
        [194, 215, 172, ..., 205, 196, 216],
        ...,
        [175, 189, 138, ..., 166, 222, 227],
        [164, 180, 129, ..., 204, 219, 231],
        [177, 184, 126, ..., 206, 224, 230]],

       [[208, 232, 179, ..., 202, 217, 198],
        [210, 236, 182, ..., 213, 220, 199],
        [211, 226, 188, ..., 210, 206, 218],
        ...,
        [174, 188, 136, ..., 177, 210, 236],
        [166, 198, 131, ..., 195, 208, 234],
        [177, 197, 138, ..., 193, 219, 231]],

       ...,

       [[175, 233, 185, ..., 196, 224, 240],
        [173, 222, 186, ..., 179, 234, 241],
        [181, 224, 179, ..., 169, 227, 235

In [12]:


imagepath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input.tif'
labelpath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-labels\train-labels.tif'
promappath = labelpath



FOV, FOV_label,FOV_IM, Image = get_data(imagepath, labelpath, promappath,'NONE',[15,15,7], False)

Images are read now


MemoryError: 

In [11]:
def get_data(input_image = None ,input_label = None, input_probability_map= None, Padding = 'NONE', Size = None ,Sample = False, Stride = 1, Depth_Stride = 1 ):
	"""
	This function is the preprocess of the input image,
	it will return 4 np.array: FOV, Cropped Original Image, Cropped label and Full-sized Original Image

	input_path : path of the folder of the input training image, from parser
	Padding : The model of paading used here, from parser
	Size : The size of Field Of View(FOV), from config

	Sample : Using sample mode or not, from config
	Stride : Stride on Height and Width, from config
	Depth_Stride : Stride on Depth, from config
	"""

	if Sample == True:
		raise ValueError("Sample mode has not been implemented")
	if Size == None or len(Size) != 3:
		raise ValueError("Please specify the size of FOV, it must be in the format of [x,y,z]")

	# prefilepath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input-split\train-input-'

	## Read the image, label and probability map
	Image = tiff.imread(input_image)
	Label = tiff.imread(input_label)
	Promap = tiff.imread(input_probability_map)
	Image = np.transpose(Image, (2,0,1)).astype('int8')
	Label = np.transpose(Label, (2,0,1)).astype('int8')
	Promap = np.transpose(Promap, (2,0,1)).astype('int8')

	print("Images are read now")

	if Image.shape != Label.shape or Image.shape != Promap.shape or Label.shape != Promap.shape:
		raise ValueError("ValueError: Image, Promap and Label should have the same size with each other")


	r_xy = int((Size[0]-1)/2)
	r_z = int((Size[2]-1) /2)
	if Padding == 'NONE':
		Start_xy = int((Size[0]-1)/2)
		End_xy = int(Image.shape[0] - (Size[0]-1)/2)
		Start_z = int((Size[2]-1)/2)
		End_z = int(Image.shape[2] - (Size[2]-1)/2)

		FOV = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')
		FOV_label = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')
		FOV_Im  = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')

		for i in range(Start_xy, End_xy):
			for j in range(Start_z, End_xy):
				FOV[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Promap[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]
				FOV_label[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Label[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]
				FOV_Im[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Image[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]

		return FOV, FOV_label, FOV_Im, Image
	elif Padding == 'SAME':
		FOV = np.zeros((Promap.shape[0],Promap.shape[1],Promap.shape[2], Size[0], Size[1], Size[2])).astype('int8')
		FOV_label = np.zeros((Label.shape[0],Label.shape[1],Label.shape[2], Size[0], Size[1], Size[2])).astype('int8')
		FOV_Im  =  np.zeros((Image.shape[0],Image.shape[1],Image.shape[2], Size[0], Size[1], Size[2])).astype('int8')

		for i in range(0,Image.shape[0]):
			for j in range(0, Image.shape[2]):
				Start_xy = int(max(0, i- r_xy))
				End_xy = int(min(i+r_xy+1,Promap.shape[1]))
				Start_z = int(max(0,j-r_z))
				End_z = int(min(j+r_z+1,Promap.shape[2]))

				FOV[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Promap[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]
				FOV_label[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Label[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]
				FOV_Im[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Image[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]

		return FOV, FOV_label, FOV_Im, Image
	else:
		raise ValueError("Padding only support SAME and NONE now")

In [3]:

input_image = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input\train-input.tif' 
input_label = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-labels\train-labels.tif'
input_probability_map= r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-labels\train-labels.tif'
Padding = 'NONE'
Size = [15,15,7]
Sample = False
Stride = 1
Depth_Stride = 1 





if Sample == True:
    raise ValueError("Sample mode has not been implemented")
if Size == None or len(Size) != 3:
    raise ValueError("Please specify the size of FOV, it must be in the format of [x,y,z]")

# prefilepath = r'C:\Users\sunzh\CS636\Summer project\BPN\data\train-input-split\train-input-'

## Read the image, label and probability map
Image = tiff.imread(input_image)
Label = tiff.imread(input_label)
Promap = tiff.imread(input_probability_map)
Image = np.transpose(Image, (2,0,1)).astype('int8')
Label = np.transpose(Label, (2,0,1)).astype('int8')
Promap = np.transpose(Promap, (2,0,1)).astype('int8')

print("Images are read now")

if Image.shape != Label.shape or Image.shape != Promap.shape or Label.shape != Promap.shape:
    raise ValueError("ValueError: Image, Promap and Label should have the same size with each other")


r_xy = int((Size[0]-1)/2)
r_z = int((Size[2]-1) /2)
if Padding == 'NONE':
    Start_xy = int((Size[0]-1)/2)
    End_xy = int(Image.shape[0] - (Size[0]-1)/2)
    Start_z = int((Size[2]-1)/2)
    End_z = int(Image.shape[2] - (Size[2]-1)/2)

    FOV = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')
    FOV_label = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')
    FOV_Im  = np.zeros((End_xy - Start_xy +1, End_xy - Start_xy+1, End_z - Start_z +1, Size[0], Size[1], Size[2])).astype('int8')

    for i in range(Start_xy, End_xy):
        for j in range(Start_z, End_xy):
            FOV[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Promap[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]
            FOV_label[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Label[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]
            FOV_Im[i-Start_xy,i-Start_z,j-Start_z,:,:,:] = Image[i-Start_xy:i-Start_xy+Size[0], i-Start_xy:i-Start_xy+Size[1], j-Start_z:j-Start_z+Size[2] ]

#     return FOV, FOV_label, FOV_Im, Image
elif Padding == 'SAME':
    FOV = np.zeros((Promap.shape[0],Promap.shape[1],Promap.shape[2], Size[0], Size[1], Size[2])).astype('int8')
    FOV_label = np.zeros((Label.shape[0],Label.shape[1],Label.shape[2], Size[0], Size[1], Size[2])).astype('int8')
    FOV_Im  =  np.zeros((Image.shape[0],Image.shape[1],Image.shape[2], Size[0], Size[1], Size[2])).astype('int8')

    for i in range(0,Image.shape[0]):
        for j in range(0, Image.shape[2]):
            Start_xy = int(max(0, i- r_xy))
            End_xy = int(min(i+r_xy+1,Promap.shape[1]))
            Start_z = int(max(0,j-r_z))
            End_z = int(min(j+r_z+1,Promap.shape[2]))

            FOV[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Promap[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]
            FOV_label[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Label[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]
            FOV_Im[i, i, j, r_xy-(i-Start_xy):r_xy+(End_xy-i),r_xy-(i-Start_xy):r_xy+(End_xy-i), r_z-(i-Start_z):r_z+(End_z-i)] = Image[Start_xy:End_xy, Start_xy:End_xy, Start_z:End_z]

#     return FOV, FOV_label, FOV_Im, Image
else:
    raise ValueError("Padding only support SAME and NONE now")

Images are read now


MemoryError: 

In [6]:
import tensorflow.keras.preprocessing.image.

ModuleNotFoundError: No module named 'tensorflow.keras.preprocessing.image.DirectoryIterator'